name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Build Docker image
      run: docker build -t pahchaan2018/networthapp .

    - name: Push Docker image
      run: docker push pahchaan2018/networthapp
      env:
        DOCKER_USERNAME: pahchaan2018
        DOCKER_PASSWORD: Surajs338@%
